server:
  port: 8765
spring:
  application:
    name: turbine
turbine:
  app-config: collection, report
  cluster-name-expression: new String("default")
  aggregator:
    cluster-config: default
  instanceUrlSuffix: /actuator/hystrix.stream
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka