
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sugare/config-repo
          search-paths:
          - respo
  boot:
    admin:
      client:
        url: http://localhost:8788
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"

