apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admin-server
  labels:
    app: admin-server
spec:
  template:
    metadata:
      name: admin-server
      labels:
        app: admin-server
    spec:
      containers:
      - name: admin-server
        image: test.caicloudprivatetest.com/library/admin:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8788
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
spec:
  type: NodePort
  ports:
  - port: 8788
    targetPort: 8788
  selector:
    app: admin-server
